### PR TITLE
Ahelp and Erase Button Sound Effect Changes

### PR DESCRIPTION
**Pull request by Verbalase**
## About the PR
Replaces the "Erase" button's sound effect and the ahelp sound effect with Goonstation's.

## Why / Balance
Shits and giggles.

## Technical details
Simple file replacements.

## Media
None?

## Requirements
- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
Should be none.

**Changelog**

:cl:
- tweak: Ahelp and erase verb sound effects.

### CODE REVIEW

**Comment by GroggleG** [comment]
remove the ahelp sound!

**Review by GroggleG — CHANGES_REQUESTED** [review]
Remove tha facken adminhelp sound!

**Comment by Verbalase** [comment]
> Remove tha facken adminhelp sound!

fixed, now merge my pr!!!

**Review by GroggleG — APPROVED** [review]
Thank ye.

**Pull request merged**
